unbind C-b
set -g prefix C-u
run-shell 'tmux setenv -g TMUX_PREFIX_KEY U'
set-option -g status-bg colour211
set-option -g status-fg black
set -g pane-border-style fg=colour52
set -g pane-active-border-style fg=colour183
