
# リフレッシュの間隔を設定する(デフォルト 15秒)
set -g status-interval 1

#ヒストリサイズの設定
set-option -g history-limit 10000

#############################################
# マシン毎の設定
# 色の設定
#############################################


#デフォルト設定
#prefix key
unbind C-b
set -g prefix C-b
# カラー設定は2重に設定できないようなのでコメントアウト
#run-shell "tmux setenv -g TMUX_VERSION $(tmux -V | cut -c 6-)"
#if-shell -b '[ "$(echo "$TMUX_VERSION < 1.9" | bc)" -eq 1 ]' \
#	"set-option -g status-bg colour160; \
#	 set-option -g status-fg black; \
#	 set -g pane-border-fg colour160; \
#	 set -g pane-active-border-fg colour210;" \
#	"set-option -g status-style fg=black,bg=colour160; \
#	 set-option -g pane-border-style fg=colour160; \
#	 set-option -g pane-active-border-style fg=colour210;"


# ホスト固有の設定
# hosts/<hostname>/tmux.conf が存在すればそれを読み込む(-q: 無ければ無視)
source-file -Fq "$DOTFILES_DIR/hosts/#{host}/tmux.conf"
#############################################

# status-right のフォーマットを指定する。
set -g status-right-length 80
set-option -g status-right \
"\"#h\" "\
"#(echo \${TMUX_PREFIX_KEY}) "\
"%Y/%m/%d %H:%M:%S#[default]"


# escape遅延設定1ms(default 500ms)
set -sg escape-time 1

# split window default %/"
bind h split-window -h \; pipe-pane -o '/bin/sh -c "while read -r LINE; do echo \"[\$(date +\"%%Y_%%m%%d_%%H%%M%%S_%%N\")] \${LINE}\" >> \${HOME}/.tmux/log/\$(date +%Y%m%d-%H%M%S)-#S-#I.#P.log; done "'
bind v split-window -v \; pipe-pane -o '/bin/sh -c "while read -r LINE; do echo \"[\$(date +\"%%Y_%%m%%d_%%H%%M%%S_%%N\")] \${LINE}\" >> \${HOME}/.tmux/log/\$(date +%Y%m%d-%H%M%S)-#S-#I.#P.log; done "'
# new window
bind c new-window \; pipe-pane -o '/bin/sh -c "while read -r LINE; do echo \"[\$(date +\"%%Y_%%m%%d_%%H%%M%%S_%%N\")] \${LINE}\" >> \${HOME}/.tmux/log/\$(date +%Y%m%d-%H%M%S)-#S-#I.#P.log; done "'

# use mouse
#set -g mode-mouse on
#set -g mouse-resize-pane on
#set -g mouse-select-pane on
#set -g mouse-select-window on

#clock
set-window-option -g clock-mode-colour colour245
