unbind C-b
set -g prefix C-k
run-shell 'tmux setenv -g TMUX_PREFIX_KEY K'
set-option -g status-bg colour87
set-option -g status-fg black
set -g pane-border-style fg=colour30
set -g pane-active-border-style fg=colour123
